### PR TITLE
change improve pages target

### PR DESCRIPTION
**Pull request by bugsounet**
Now, develop branch is online

So, let's change improve pages target to develop branch

### CODE REVIEW

**Comment by rejas** [comment]
But what happens when we merge develop into branch?

**Comment by bugsounet** [comment]
Try with a fork?

**Comment by rejas** [comment]
But the develop branch can already be found here: https://develop.docs.magicmirror.builders/ so why the change?

**Comment by bugsounet** [comment]
because it's related to this target:

image

I think it's better to edit/modify it to the develop branch and not in master

**Comment by rejas** [comment]
> I think it's better to edit/modify any pages to the develop branch and not in master

Not convinced that this is the use-case for this link. In my opinion, this link is for people that browse the webpage and want to fix a typo or some other error. They want to edit master. 

If a developer wants to fix something (add new config options in an upcoming release for example) they would probably not use that link but rather go their normal way with their IDE of choice etc.

**Comment by bugsounet** [comment]
Can I close this PR ?

**Comment by rejas** [comment]
I would say so

**Comment by bugsounet** [comment]
will not be implemented

**Pull request closed without merging**
