### PR TITLE
Update URLs to MagicMirrorOrg

### PR DESCRIPTION
**Pull request by KristjanESPERANTO**

### CODE REVIEW

**Comment by rejas** [comment]
Thanks for the quick work. Maybe we can cherrypick this commit into master since the change to the org is already "live" ?

**Comment by khassel** [comment]
upsi, overlooked `develop`, is it o.k. to merge `develop` into `master`?

**Comment by rejas** [comment]
yeah, that will be fine i guess

**Comment by khassel** [comment]
o.k., will try ...

**Comment by khassel** [comment]
done.

**Pull request merged**
