### PR TITLE
Update compliments.md

### PR DESCRIPTION
**Pull request by 3DPixel**
In the original guide, adding the compliments to the MagicMirror/config/config.js file didn't override the default compliments. By adding them to the defaults file, it works

### CODE REVIEW

**Comment by bugsounet** [comment]
> adding the compliments to the MagicMirror/config/config.js file didn't override the default compliments.

Tested with new compliments in config.js, it's works
I think you have made an error in your personal config

There is maybe an error of understanding, I will clarify the doc

sample [there](https://develop.docs.magicmirror.builders/modules/compliments.html#default-value)

maybe it's better:

```js
{
    module: "compliments",
    position: "lower_third",
    config: {
      compliments: {
        anytime: [
          "Hey there sexy!"
        ],
        morning: [
          "Good morning, handsome!",
          "Enjoy your day!",
          "How was your sleep?"
        ],
        afternoon: [
          "Hello, beauty!",
          "You look sexy!",
          "Looking good today!"
        ],
        evening: [
          "Wow, you look hot!",
          "You look nice!",
          "Hi, sexy!"
        ],
        "....-01-01": [
          "Happy new year!"
        ]
      }
    }
}
```

@rejas: what do you thiink about this ?

**Comment by rejas** [comment]
@bugsounet is right, the moduel works as expected, no need to change the defaults. happy to get a PR for this to clear up

**Comment by 3DPixel** [comment]
I edited the config/compliments.js file and ran the npm check utility and everything checked out but none of the custom compliments worked and the defaults ran instead.

**Comment by bugsounet** [comment]
# Configuration tested (in config.js)

```js
		{
			module: "compliments",
			position: "lower_third",
			animateIn: "bounceInDown",
			animateOut: "bounceOutUp",
			config: {
				updateInterval: 500,
				fadeSpeed: 200,
				compliments: {
			        anytime: [
			          "anytime1",
			          "Really ?",
			          "there is not default!!!"
			        ],
			        morning: [
			          "morning1",
			          "morning2",
			          "morning3"
			        ],
			        afternoon: [
			          "afternoon1",
			          "afternoon2",
			          "afternoon3"
			        ],
			        evening: [
			          "evening1",
			          "evening2",
			          "evening3"
			        ],
			        "....-01-01": [
			          "!!!! Happy new year !!!!!"
			        ]
			      }
			}
			
		},
```

## Result:

ezgif com-gif-maker

That you can see, there is no default and the module works as expected.
I just speed up interval of update

**Comment by rejas** [comment]
> I edited the config/compliments.js file

Stange filename, you should edit config/config.js

**Comment by khassel** [comment]
what is the content beside the unwanted filename change? It's hard to see, looks like only format has changed (which will be reverted when lintered).

**Comment by 3DPixel** [comment]
Apologies, it was the config/config.js
I typed ‘compliements.js’ as I’d not got the details to hand and thought it was the right file name.. of the top of my head.

Back to the original topic.
I don’t know why it didn’t work for me, I had just copied the template from the documentation, ran the config checker and it checked out but didn’t work.

As the file mentioned previously did work, is there a reason that there needs to be 2 files that do the same thing? Thanks 😊

**Comment by 3DPixel** [comment]
Sorry, what is ‘lintered’, is that GitHub lingo?
I’m new to GitHub so just getting to grips with it.
Thanks

**Comment by sdetweil** [comment]
this is a year old, we've updated compliments since then.. are all these updates taken care of? so we can close this

**Comment by rejas** [comment]
I dont see any reason for this PR, maybe the OP can open an issue if their problem still exists?

**Pull request closed without merging**
